[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_hello_world = "5PPuQh2xVMkd69tdsnR48HZoFRH4ZM8FvCYt3vgq9sxJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/eren/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
